# Generated by Django 4.2.30 on 2026-09-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
