# Generated by Django 4.2.30 on 2026-09-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0003_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2),
        ),
    ]
